<?php

namespace Database\Seeders;

use App\Models\LegalPrecedent;
use Illuminate\Database\Seeder;

/**
 * Seeds the legal_precedents table with test data.
 *
 * Contains case law from:
 * - USRH (Ustavni sud Republike Hrvatske)
 * - VSRH (Vrhovni sud Republike Hrvatske)
 * - ECHR (European Court of Human Rights)
 */
class LegalPrecedentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $precedents = [
            // ============================================================
            // USRH (Ustavni sud Republike Hrvatske)
            // ============================================================
            [
                'case_number' => 'U-III-3071/2006',
                'court' => 'USRH',
                'court_full' => 'Ustavni sud Republike Hrvatske',
                'decision_date' => '2009-03-18',
                'published_in' => 'NN 42/2009',
                'applicant' => null,
                'respondent' => null,
                'echr_app_number' => null,
                'legal_issue' => 'Pogresna uputa o pravnom lijeku i pravo na pravicno sudjenje',
                'key_holding' => 'Pogresna ili izostala uputa o pravnom lijeku cini povredu cl.18 st.1 i cl.29 st.1 Ustava. Stranka ne smije trpjeti stetne posljedice zbog postupanja po pogresnoj uputi.',
                'key_quote' => 'Ustavni sud na kraju podsjeca da je temeljni zahtjev svakog pravnog poretka utemeljenog na nacelu vladavine prava da sudovi poznaju propise koje primjenjuju u konkretnim slucajevima i da daju zakonitu i pravilnu uputu o pravnom lijeku. Stoga stranke zbog postupanja po pogresnoj uputi o pravnom lijeku koju daju sudovi ne smiju trpjeti stetne posljedice.',
                'quote_language' => 'hr',
                'relevance_to_case' => 'Direktno primjenjiva: ako pogresna uputa = povreda, tada NIKAKVA uputa (email odbijanje) = a fortiori teza povreda. Koristiti u ustavnoj tuzbi kao stozernu presudu.',
                'strength' => 'devastating',
                'articles_interpreted' => ['Ustav cl.18 st.1', 'Ustav cl.29 st.1'],
                'argument_types' => ['right_to_appeal', 'fair_trial'],
                'tags' => ['ustavni_sud', 'predsjednik_suda', 'ombudsman', 'all_profiles'],
                'source_url' => 'https://narodne-novine.nn.hr/clanci/sluzbeni/2009_04_42_983.html',
                'nn_reference' => 'NN 42/2009',
            ],
            [
                'case_number' => 'U-III-2258/2018',
                'court' => 'USRH',
                'court_full' => 'Ustavni sud Republike Hrvatske',
                'decision_date' => '2020-02-26',
                'published_in' => 'NN 37/2020',
                'applicant' => null,
                'respondent' => null,
                'echr_app_number' => null,
                'legal_issue' => 'Obrazlozenje sudskih odluka i zabrana arbitrarnosti',
                'key_holding' => 'Obrazlozenja sudskih odluka moraju sadrzavati dostatne, ozbiljne i relevantne razloge. Nedostatak razloga = arbitrarnost.',
                'key_quote' => 'Prava zajamcena Ustavom i medunarodnim pravnim aktima... bila bi iluzorna i teorijska, a ne stvarna i ucinkovita, kada ne bi postojala obveza sudbene vlasti da... svoje odluke obrazlozi.',
                'quote_language' => 'hr',
                'relevance_to_case' => 'Email bez obrazlozenja = arbitrarna odluka. Koristiti za cl.29 argument i za argument da prava postaju "iluzorna i teorijska".',
                'strength' => 'devastating',
                'articles_interpreted' => ['Ustav cl.29 st.1'],
                'argument_types' => ['fair_trial', 'reasoned_decision'],
                'tags' => ['ustavni_sud', 'predsjednik_suda', 'ombudsman', 'all_profiles'],
                'source_url' => 'https://narodne-novine.nn.hr/clanci/sluzbeni/2020_03_37_813.html',
                'nn_reference' => 'NN 37/2020',
            ],
            [
                'case_number' => 'U-I-4497/2005',
                'court' => 'USRH',
                'court_full' => 'Ustavni sud Republike Hrvatske',
                'decision_date' => '2006-11-22',
                'published_in' => 'NN 2/2007',
                'applicant' => null,
                'respondent' => null,
                'echr_app_number' => null,
                'legal_issue' => 'Ustavnost pretrage doma i zahtjev za pisani nalog',
                'key_holding' => 'Cl.34 Ustava zahtijeva obrazlozeni pisani sudski nalog za pretragu doma. Sudska kontrola pretrage mora biti stvarna, ne formalna.',
                'key_quote' => 'Sudska kontrola naloga za pretragu mora biti stvarna i ucinkovita, a nalog mora biti pisan i obrazlozen kako bi se mogla provjeriti zakonitost pretrage.',
                'quote_language' => 'hr',
                'relevance_to_case' => 'Podrzava argument da cl.34 zahtijeva mogucnost naknadne provjere zakonitosti pretrage — sto je nemoguce bez uvida u spis.',
                'strength' => 'strong',
                'articles_interpreted' => ['Ustav cl.34'],
                'argument_types' => ['right_to_home', 'unlawful_search'],
                'tags' => ['ustavni_sud', 'home_search', 'echr_application'],
                'source_url' => null,
                'nn_reference' => 'NN 2/2007',
            ],

            // ============================================================
            // VSRH (Vrhovni sud Republike Hrvatske)
            // ============================================================
            [
                'case_number' => 'I Kž-135/2018',
                'court' => 'VSRH',
                'court_full' => 'Vrhovni sud Republike Hrvatske',
                'decision_date' => '2018-05-27',
                'published_in' => null,
                'applicant' => null,
                'respondent' => null,
                'echr_app_number' => null,
                'legal_issue' => 'Nezakonita pretraga provedena pod krinkom ocevida',
                'key_holding' => 'Pretraga provedena pod krinkom "ocevida" bez naredbe za pretragu = nezakonita. Svi dokazi prikupljeni takvom pretragom su nezakoniti po cl.10 ZKP.',
                'key_quote' => 'Pretraga provedena bez valjane sudske naredbe, pa makar bila nazvana ocevidom, ne moze biti temelj zakonitim dokazima.',
                'quote_language' => 'hr',
                'relevance_to_case' => 'Ako analiza naredbe pokaze procesne nedostatke, ova presuda podrzava argument za izdvajanje. Bez uvida — ne mozemo ni analizirati.',
                'strength' => 'strong',
                'articles_interpreted' => ['ZKP cl.10'],
                'argument_types' => ['exclusion_of_evidence', 'unlawful_search'],
                'tags' => ['izdvajanje_dokaza', 'kazneni_sud_motion', 'dorh_production'],
                'source_url' => null,
                'nn_reference' => null,
            ],
            [
                'case_number' => 'I Kž-Us 113/10',
                'court' => 'VSRH',
                'court_full' => 'Vrhovni sud Republike Hrvatske',
                'decision_date' => '2010-09-28',
                'published_in' => null,
                'applicant' => null,
                'respondent' => null,
                'echr_app_number' => null,
                'legal_issue' => 'Zalba protiv odbijanja izdvajanja nezakonitih dokaza',
                'key_holding' => 'Protiv rjesenja kojim se odbija prijedlog za izdvajanje nezakonitih dokaza dopustena je zalba.',
                'key_quote' => 'Protiv rjesenja o odbijanju prijedloga za izdvajanje nezakonitih dokaza dopustena je zalba.',
                'quote_language' => 'hr',
                'relevance_to_case' => 'Vazno za proceduralni aspekt: cak i ako kazneni sud odbije izdvajanje, postoji zalba — za razliku od sadasnje situacije gdje nema NI odluke NI zalbe.',
                'strength' => 'moderate',
                'articles_interpreted' => ['ZKP cl.10'],
                'argument_types' => ['right_to_appeal', 'exclusion_of_evidence'],
                'tags' => ['izdvajanje_dokaza', 'kazneni_sud_motion'],
                'source_url' => null,
                'nn_reference' => null,
            ],
            [
                'case_number' => 'Pravno shvacanje od 8.3.2019.',
                'court' => 'VSRH',
                'court_full' => 'Vrhovni sud Republike Hrvatske',
                'decision_date' => '2019-03-08',
                'published_in' => 'Kazneni odjel VSRH',
                'applicant' => null,
                'respondent' => null,
                'echr_app_number' => null,
                'legal_issue' => 'Obveza suda da odluci o prijedlogu za izdvajanje dokaza',
                'key_holding' => 'Sud mora odluciti o svakom prijedlogu za izdvajanje nezakonitih dokaza. Odbijanje bez razmatranja = bitna povreda odredaba kaznenog postupka.',
                'key_quote' => 'Sud o svakom takvom prijedlogu mora odluciti, osim ako ne utvrdi da je rijec o zlouporabi prava.',
                'quote_language' => 'hr',
                'relevance_to_case' => 'Ako buduca obrana podnese prijedlog za izdvajanje, sud ga NE smije ignorirati. Ovo je backup za kazneni postupak.',
                'strength' => 'strong',
                'articles_interpreted' => ['ZKP cl.10'],
                'argument_types' => ['exclusion_of_evidence', 'procedural_fairness'],
                'tags' => ['izdvajanje_dokaza', 'kazneni_sud_motion'],
                'source_url' => 'https://www.vsrh.hr/CustomPages/Static/HRV/Files/Radovi/DKos/Nezakoniti%20dokazi-Opatija%202017.pdf',
                'nn_reference' => null,
            ],

            // ============================================================
            // ECHR (European Court of Human Rights)
            // ============================================================
            [
                'case_number' => 'Garcia Alva v. Germany',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2001-02-13',
                'published_in' => 'ECHR Reports',
                'applicant' => 'Garcia Alva',
                'respondent' => 'Germany',
                'echr_app_number' => '23541/94',
                'legal_issue' => 'Equality of arms and access to the investigation file',
                'key_holding' => 'Equality of arms is not ensured if counsel is denied access to documents essential to challenge the lawfulness of detention. Investigation secrecy does not justify a total denial of access.',
                'key_quote' => 'Equality of arms is not ensured if counsel is denied access to those documents in the investigation file which are essential in order effectively to challenge the lawfulness of his client\'s detention.',
                'quote_language' => 'en',
                'relevance_to_case' => 'STOZERNA ECHR presuda za nas slucaj. Direktno primjenjiva: branitelju je uskracen pristup spisu pretrage koji je bitan za osporavanje zakonitosti. Koristiti u ECHR prijavi i ustavnoj tuzbi.',
                'strength' => 'devastating',
                'articles_interpreted' => ['ECHR Art.5 §4', 'ECHR Art.6'],
                'argument_types' => ['equality_of_arms', 'file_access', 'fair_trial'],
                'tags' => ['echr_application', 'ustavni_sud', 'dorh_production', 'all_profiles'],
                'source_url' => 'https://hudoc.echr.coe.int/eng?i=001-59208',
                'nn_reference' => null,
            ],
            [
                'case_number' => 'Rowe and Davis v. United Kingdom',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2000-02-16',
                'published_in' => 'ECHR Reports 2000-II',
                'applicant' => 'Rowe and Davis',
                'respondent' => 'United Kingdom',
                'echr_app_number' => '28901/95',
                'legal_issue' => 'Non-disclosure of evidence and equality of arms',
                'key_holding' => 'The prosecution must disclose material evidence for or against the accused. If the prosecution alone decides on disclosure, Article 6 is violated unless strict safeguards exist.',
                'key_quote' => 'The prosecution authorities should disclose to the defence all material evidence in their possession for or against the accused.',
                'quote_language' => 'en',
                'relevance_to_case' => 'Primjenjiva na DORH zahtjev: DORH mora pribaviti i objelodaniti spis pretrage. Ako DORH sam odlucuje sto obrana smije vidjeti = "judge in own cause".',
                'strength' => 'devastating',
                'articles_interpreted' => ['ECHR Art.6'],
                'argument_types' => ['non_disclosure', 'equality_of_arms', 'fair_trial'],
                'tags' => ['echr_application', 'dorh_production'],
                'source_url' => 'https://hudoc.echr.coe.int/eng?i=001-58496',
                'nn_reference' => null,
            ],
            [
                'case_number' => 'Modestou v. Greece',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2017-03-16',
                'published_in' => null,
                'applicant' => 'Modestou',
                'respondent' => 'Greece',
                'echr_app_number' => '51693/13',
                'legal_issue' => 'Overbroad search warrants and proportionality',
                'key_holding' => 'A broadly worded search warrant without specific description of items sought may breach Article 8 when the intrusion is disproportionate.',
                'key_quote' => 'The search warrant was drafted in overly broad terms and did not provide sufficient specification of the objects sought, which rendered the interference disproportionate.',
                'quote_language' => 'en',
                'relevance_to_case' => 'Podrzava argument da bez uvida u naredbu ne mozemo provjeriti je li bila specificna ili opcenita. Ako je bila opcenita kao u Modestou = cl.8 povreda.',
                'strength' => 'strong',
                'articles_interpreted' => ['ECHR Art.8'],
                'argument_types' => ['unlawful_search', 'proportionality', 'right_to_home'],
                'tags' => ['echr_application', 'izdvajanje_dokaza', 'home_search'],
                'source_url' => 'https://hudoc.echr.coe.int/eng?i=001-172280',
                'nn_reference' => null,
            ],
            [
                'case_number' => 'Dorož v. Poland',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2020-10-29',
                'published_in' => null,
                'applicant' => 'Doroż',
                'respondent' => 'Poland',
                'echr_app_number' => '71205/11',
                'legal_issue' => 'Search proportionality and sufficient reasons',
                'key_holding' => 'A search not justified by relevant and sufficient reasons is disproportionate and violates Article 8.',
                'key_quote' => 'The search of the applicant\'s residence was not justified by "relevant" and "sufficient" reasons and the principle of proportionality had not been complied with.',
                'quote_language' => 'en',
                'relevance_to_case' => 'Referenca za visinu odstete u ECHR prijavi + argument da naredba mora biti temeljena na "relevantnim i dovoljnim razlozima" — bez uvida ne mozemo to provjeriti.',
                'strength' => 'strong',
                'articles_interpreted' => ['ECHR Art.8'],
                'argument_types' => ['unlawful_search', 'proportionality', 'right_to_home'],
                'tags' => ['echr_application', 'home_search'],
                'source_url' => 'https://hudoc.echr.coe.int/eng?i=001-205528',
                'nn_reference' => null,
            ],
            [
                'case_number' => 'Đorđević v. Croatia',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2012-07-24',
                'published_in' => null,
                'applicant' => 'Đorđević',
                'respondent' => 'Croatia',
                'echr_app_number' => '41526/10',
                'legal_issue' => 'Effective remedy and positive obligations',
                'key_holding' => 'Croatia violated Article 13 because the applicants did not have an effective remedy to protect their rights.',
                'key_quote' => 'The Court finds that the applicants did not have an effective remedy in respect of their complaints, contrary to Article 13 of the Convention.',
                'quote_language' => 'en',
                'relevance_to_case' => 'Dokazuje OBRAZAC — Hrvatska ima sistemski problem s djelotvornim pravnim lijekovima. Koristiti za cl.13 argument u ECHR prijavi.',
                'strength' => 'strong',
                'articles_interpreted' => ['ECHR Art.13'],
                'argument_types' => ['effective_remedy', 'positive_obligation'],
                'tags' => ['echr_application'],
                'source_url' => 'https://hudoc.echr.coe.int/eng?i=001-112322',
                'nn_reference' => null,
            ],
            [
                'case_number' => 'F.S. v. Croatia',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2023-12-05',
                'published_in' => null,
                'applicant' => 'F.S.',
                'respondent' => 'Croatia',
                'echr_app_number' => '8857/16',
                'legal_issue' => 'Insufficient counterbalancing safeguards in criminal proceedings',
                'key_holding' => 'Domestic counterbalancing measures were insufficiently effective; the applicant was given no factual elements underlying the decision.',
                'key_quote' => 'The counterbalancing safeguards were insufficiently effective, and the applicant was not provided with any factual elements on which the decision was based.',
                'quote_language' => 'en',
                'relevance_to_case' => 'IZUZETNO RELEVANTNA — gotovo identicna cinjenicna situacija: uskrata pristupa materijalima bez obrazlozenja. Koristiti kao recentnu presudu protiv Hrvatske.',
                'strength' => 'devastating',
                'articles_interpreted' => ['ECHR Art.6'],
                'argument_types' => ['fair_trial', 'file_access'],
                'tags' => ['echr_application', 'ustavni_sud'],
                'source_url' => null,
                'nn_reference' => null,
            ],
            [
                'case_number' => 'Dvorski v. Croatia [GC]',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2015-11-20',
                'published_in' => null,
                'applicant' => 'Dvorski',
                'respondent' => 'Croatia',
                'echr_app_number' => '25703/11',
                'legal_issue' => 'Waiver of defence rights and access to counsel',
                'key_holding' => 'Strict standards apply to any waiver of fair-trial guarantees; rights cannot be sidelined informally.',
                'key_quote' => 'Neither the letter nor the spirit of Article 6 allows the waiver of fundamental defence rights to be presumed in an implicit manner.',
                'quote_language' => 'en',
                'relevance_to_case' => 'Grand Chamber presuda protiv Hrvatske — pojacava argument da se pravo na pristup spisu ne smije uskratiti neformalnim emailom.',
                'strength' => 'moderate',
                'articles_interpreted' => ['ECHR Art.6'],
                'argument_types' => ['fair_trial', 'defense_rights'],
                'tags' => ['echr_application'],
                'source_url' => null,
                'nn_reference' => null,
            ],
            [
                'case_number' => 'Horvat v. Croatia',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2001-07-26',
                'published_in' => null,
                'applicant' => 'Horvat',
                'respondent' => 'Croatia',
                'echr_app_number' => '51585/99',
                'legal_issue' => 'Effectiveness of remedies in practice',
                'key_holding' => 'Lack of case-law may indicate practical uncertainty of a remedy, undermining its effectiveness.',
                'key_quote' => 'The absence of further case-law indicates the present uncertainty of a remedy in practical terms.',
                'quote_language' => 'en',
                'relevance_to_case' => 'Fundamentalna cl.13 presuda protiv Hrvatske. Neformalno email odbijanje stvara "neizvjesnost pravnog lijeka u prakticnom smislu".',
                'strength' => 'strong',
                'articles_interpreted' => ['ECHR Art.13'],
                'argument_types' => ['effective_remedy', 'access_to_court'],
                'tags' => ['echr_application'],
                'source_url' => null,
                'nn_reference' => null,
            ],
            [
                'case_number' => 'Dragojević v. Croatia',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2015-01-15',
                'published_in' => null,
                'applicant' => 'Dragojević',
                'respondent' => 'Croatia',
                'echr_app_number' => '68955/11',
                'legal_issue' => 'Deficient search warrants and exclusion of evidence',
                'key_holding' => 'Retroactive justifications for deficient warrants are not acceptable. An inadequately reasoned search warrant may violate Article 8 and require exclusion of evidence.',
                'key_quote' => 'The Court considers that the search carried out at the applicant\'s home was not "in accordance with the law" within the meaning of Article 8 of the Convention.',
                'quote_language' => 'en',
                'relevance_to_case' => 'Ključno za izdvajanje dokaza — ako naredba nije adekvatno obrazlozena (sto ne mozemo provjeriti bez uvida), dokazi su nezakoniti. Presuda PROTIV HRVATSKE.',
                'strength' => 'devastating',
                'articles_interpreted' => ['ECHR Art.8'],
                'argument_types' => ['unlawful_search', 'exclusion_of_evidence'],
                'tags' => ['izdvajanje_dokaza', 'echr_application', 'home_search'],
                'source_url' => null,
                'nn_reference' => null,
            ],
            [
                'case_number' => 'Bašić v. Croatia',
                'court' => 'ECHR',
                'court_full' => 'European Court of Human Rights',
                'decision_date' => '2018-10-25',
                'published_in' => null,
                'applicant' => 'Bašić',
                'respondent' => 'Croatia',
                'echr_app_number' => '22251/13',
                'legal_issue' => 'Insufficiently reasoned surveillance orders',
                'key_holding' => 'An inadequately reasoned interception order violates Article 8. The same logic applies to search warrants.',
                'key_quote' => 'The interception order lacked adequate reasons and therefore did not meet the quality-of-law requirements under Article 8.',
                'quote_language' => 'en',
                'relevance_to_case' => 'Jos jedna presuda PROTIV HRVATSKE na temu neadekvatnog obrazlozenja naloga. Pojacava Dragojevic argument.',
                'strength' => 'strong',
                'articles_interpreted' => ['ECHR Art.8'],
                'argument_types' => ['unlawful_search', 'privacy'],
                'tags' => ['izdvajanje_dokaza', 'echr_application'],
                'source_url' => null,
                'nn_reference' => null,
            ],
        ];

        foreach ($precedents as $precedent) {
            // ECHR entries with app numbers use echr_app_number as stable key,
            // so case_number spelling corrections don't create duplicates.
            if (! empty($precedent['echr_app_number'])) {
                // Remove any stale alias with old case_number but same app number
                LegalPrecedent::where('echr_app_number', $precedent['echr_app_number'])
                    ->where('court', $precedent['court'])
                    ->where('case_number', '!=', $precedent['case_number'])
                    ->delete();

                LegalPrecedent::updateOrCreate(
                    [
                        'echr_app_number' => $precedent['echr_app_number'],
                        'court' => $precedent['court'],
                    ],
                    $precedent
                );
            } else {
                LegalPrecedent::updateOrCreate(
                    [
                        'case_number' => $precedent['case_number'],
                        'court' => $precedent['court'],
                    ],
                    $precedent
                );
            }
        }
    }
}
