<?php

namespace App\Contracts\Services;

/**
 * AgentToolboxInterface
 *
 * Provides core tooling capabilities for AI agents including:
 * - Vector search across knowledge bases
 * - Law and court decision lookups
 * - Graph database queries
 * - Web fetching
 * - Note saving and insights retrieval
 */
interface AgentToolboxInterface
{
    /**
     * Perform vector similarity search across knowledge bases
     *
     * @param  string  $query  Search query text
     * @param  array  $options  Search options (limit, threshold, filters, etc.)
     * @return array Search results with scores and metadata
     */
    public function vectorSearch(string $query, array $options = []): array;

    /**
     * Look up a specific law by number and jurisdiction
     *
     * @param  string  $lawNumber  Law identifier (e.g., "ZKP Članak 9")
     * @param  string|null  $jurisdiction  Jurisdiction filter (default: Croatia)
     * @return array Law details including full text and metadata
     */
    public function lawLookup(string $lawNumber, ?string $jurisdiction = null): array;

    /**
     * Look up court decisions by criteria
     *
     * @param  array  $criteria  Search criteria (court, date, case_number, etc.)
     * @return array Matching court decisions
     */
    public function decisionLookup(array $criteria): array;

    /**
     * Execute a Cypher query against the Neo4j graph database
     *
     * @param  string  $cypher  Cypher query string
     * @param  array  $parameters  Query parameters
     * @return array Query results as array of nodes/relationships
     */
    public function graphQuery(string $cypher, array $parameters = []): array;

    /**
     * Fetch content from a URL
     *
     * @param  string  $url  URL to fetch
     * @param  array  $options  Fetch options (timeout, headers, etc.)
     * @return array Fetched content and metadata
     */
    public function webFetch(string $url, array $options = []): array;

    /**
     * Retrieve recent insights generated by agents
     *
     * @param  string  $agentName  Agent identifier
     * @param  array  $filters  Filter criteria (date, topic, etc.)
     * @return array Recent insights with metadata
     */
    public function getRecentInsights(string $agentName, array $filters = []): array;

    /**
     * Save a note or insight generated by an agent
     *
     * @param  string  $agentName  Agent identifier
     * @param  string  $content  Note content
     * @param  array  $options  Storage options (tags, metadata, etc.)
     * @return array Saved note details including ID
     */
    public function noteSave(string $agentName, string $content, array $options = []): array;
}
