<?php

namespace App\Agents\Validation;

/**
 * Validates agent plan structure against JSON schema
 *
 * This validator ensures that plans generated by autonomous agents
 * conform to the expected structure before execution.
 */
class AgentPlanValidator
{
    /**
     * Valid tools that can be used in action plans
     */
    protected const VALID_TOOLS = [
        'vector_search',
        'law_vector_search',
        'law_keyword_search',
        'law_hybrid_search',
        'law_lookup',
        'law_get_article',
        'decision_vector_search',
        'decision_keyword_search',
        'decision_hybrid_search',
        'decision_lookup',
        'decision_get',
        'case_vector_search',
        'case_search',
        'case_document_search',
        'graph_query',
        'web_fetch',
        'note_save',
    ];

    /**
     * Maximum allowed actions per plan
     */
    protected int $maxActions = 10;

    /**
     * Minimum allowed actions per plan (unless should_stop is true)
     */
    protected int $minActions = 1;

    /**
     * Validation errors
     */
    protected array $errors = [];

    /**
     * Validation warnings (non-critical issues)
     */
    protected array $warnings = [];

    /**
     * Validate a plan structure
     *
     * @param  array  $plan  The plan to validate
     * @return bool True if valid, false otherwise
     */
    public function validate(array $plan): bool
    {
        $this->errors = [];
        $this->warnings = [];

        // 1. Validate plan logic
        if (! $this->validatePlanLogic($plan)) {
            return false;
        }

        // 2. Validate actions
        if (! $this->validateActions($plan['actions'] ?? [])) {
            return false;
        }

        return true;
    }

    /**
     * Validate plan logic
     */
    protected function validatePlanLogic(array $plan): bool
    {
        $valid = true;

        // Check required fields
        if (empty($plan['reasoning'])) {
            $this->errors[] = 'Plan must have non-empty reasoning';
            $valid = false;
        }

        // Validate reasoning length
        if (isset($plan['reasoning']) && strlen($plan['reasoning']) < 10) {
            $this->errors[] = 'Plan reasoning must be at least 10 characters';
            $valid = false;
        }

        if (isset($plan['reasoning']) && strlen($plan['reasoning']) > 2000) {
            $this->warnings[] = 'Plan reasoning is very long (>2000 chars), consider being more concise';
        }

        // Check actions array exists
        if (! isset($plan['actions']) || ! is_array($plan['actions'])) {
            $this->errors[] = 'Plan must have an actions array';
            $valid = false;

            return $valid;
        }

        $actions = $plan['actions'];
        $shouldStop = $plan['should_stop'] ?? false;

        // If not stopping, must have at least minActions actions
        if (! $shouldStop && count($actions) < $this->minActions) {
            $this->errors[] = sprintf(
                'Plan must have at least %d action(s) when not stopping (found %d)',
                $this->minActions,
                count($actions)
            );
            $valid = false;
        }

        // Check max actions limit
        if (count($actions) > $this->maxActions) {
            $this->errors[] = sprintf(
                'Plan cannot have more than %d actions (found %d)',
                $this->maxActions,
                count($actions)
            );
            $valid = false;
        }

        // If stopping, actions should be empty (or warn if not)
        if ($shouldStop && count($actions) > 0) {
            $this->warnings[] = sprintf(
                'Plan has should_stop=true but also has %d action(s). Actions may be ignored.',
                count($actions)
            );
        }

        return $valid;
    }

    /**
     * Validate actions array
     */
    protected function validateActions(array $actions): bool
    {
        $valid = true;

        foreach ($actions as $index => $action) {
            if (! $this->validateAction($action, $index)) {
                $valid = false;
            }
        }

        return $valid;
    }

    /**
     * Validate a single action
     */
    protected function validateAction(array $action, int $index): bool
    {
        $valid = true;
        $actionNum = $index + 1;

        // Check required fields
        if (empty($action['tool'])) {
            $this->errors[] = "Action #{$actionNum}: missing required 'tool' field";
            $valid = false;
        }

        if (! isset($action['params'])) {
            $this->errors[] = "Action #{$actionNum}: missing required 'params' field";
            $valid = false;
        }

        // Validate tool name
        if (isset($action['tool'])) {
            $tool = $action['tool'];

            if (! in_array($tool, self::VALID_TOOLS, true)) {
                $this->errors[] = sprintf(
                    "Action #{$actionNum}: invalid tool '%s'. Valid tools: %s",
                    $tool,
                    implode(', ', self::VALID_TOOLS)
                );
                $valid = false;
            }

            // Validate params for specific tools
            if (isset($action['params'])) {
                if (! $this->validateToolParams($tool, $action['params'], $actionNum)) {
                    $valid = false;
                }
            }
        }

        // Check for rationale (optional but recommended)
        if (empty($action['rationale'])) {
            $this->warnings[] = "Action #{$actionNum}: missing recommended 'rationale' field";
        }

        return $valid;
    }

    /**
     * Validate tool-specific parameters
     */
    protected function validateToolParams(string $tool, $params, int $actionNum): bool
    {
        $valid = true;

        // Params must be array or object
        if (! is_array($params) && ! is_object($params)) {
            $this->errors[] = "Action #{$actionNum}: params must be an array or object";

            return false;
        }

        // Convert to array for consistent checking
        $paramsArray = is_array($params) ? $params : (array) $params;

        // Tool-specific validation
        switch ($tool) {
            case 'vector_search':
            case 'law_vector_search':
            case 'law_keyword_search':
            case 'law_hybrid_search':
            case 'decision_vector_search':
            case 'decision_keyword_search':
            case 'decision_hybrid_search':
            case 'case_vector_search':
            case 'case_search':
            case 'case_document_search':
                // These all require a 'query' parameter
                if (empty($paramsArray['query'])) {
                    $this->errors[] = "Action #{$actionNum}: {$tool} requires a 'query' parameter";
                    $valid = false;
                }
                break;

            case 'law_lookup':
                if (empty($paramsArray['law_number'])) {
                    $this->errors[] = "Action #{$actionNum}: law_lookup requires a 'law_number' parameter";
                    $valid = false;
                }
                break;

            case 'law_get_article':
                if (empty($paramsArray['doc_id'])) {
                    $this->errors[] = "Action #{$actionNum}: law_get_article requires a 'doc_id' parameter";
                    $valid = false;
                }
                break;

            case 'decision_get':
                if (empty($paramsArray['id'])) {
                    $this->errors[] = "Action #{$actionNum}: decision_get requires an 'id' parameter";
                    $valid = false;
                }
                break;

            case 'graph_query':
                if (empty($paramsArray['cypher'])) {
                    $this->errors[] = "Action #{$actionNum}: graph_query requires a 'cypher' parameter";
                    $valid = false;
                }
                break;

            case 'web_fetch':
                if (empty($paramsArray['url'])) {
                    $this->errors[] = "Action #{$actionNum}: web_fetch requires a 'url' parameter";
                    $valid = false;
                } elseif (! filter_var($paramsArray['url'], FILTER_VALIDATE_URL)) {
                    $this->errors[] = "Action #{$actionNum}: web_fetch url must be a valid URL";
                    $valid = false;
                }
                break;

            case 'note_save':
                if (empty($paramsArray['content'])) {
                    $this->errors[] = "Action #{$actionNum}: note_save requires a 'content' parameter";
                    $valid = false;
                }
                break;
        }

        return $valid;
    }

    /**
     * Get validation errors
     */
    public function getErrors(): array
    {
        return $this->errors;
    }

    /**
     * Get validation warnings
     */
    public function getWarnings(): array
    {
        return $this->warnings;
    }

    /**
     * Get all validation messages (errors + warnings)
     */
    public function getMessages(): array
    {
        return [
            'errors' => $this->errors,
            'warnings' => $this->warnings,
        ];
    }

    /**
     * Set maximum allowed actions
     */
    public function setMaxActions(int $max): self
    {
        $this->maxActions = $max;

        return $this;
    }

    /**
     * Set minimum required actions
     */
    public function setMinActions(int $min): self
    {
        $this->minActions = $min;

        return $this;
    }

    /**
     * Get list of valid tools
     */
    public static function getValidTools(): array
    {
        return self::VALID_TOOLS;
    }
}
