#!/bin/bash

# ============================================
# TodoWrite Generator from Test Failures
# ============================================
# Creates TodoWrite JSON from analyzed test failures
# for Claude to import and track
# ============================================

set -e

TASKS_FILE="./FAILING_TESTS_TASKS.md"
OUTPUT_FILE="./test-failure-todos.json"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${CYAN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║          TodoWrite Generator from Test Failures            ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

if [ ! -f "$TASKS_FILE" ]; then
    echo -e "${RED}Error: Tasks file not found: $TASKS_FILE${NC}"
    echo -e "${YELLOW}Run ./scripts/analyze-test-failures.sh first${NC}"
    exit 1
fi

# Parse tasks and create todo list
echo -e "${BLUE}Parsing tasks from ${TASKS_FILE}...${NC}"

# Extract task information
declare -a tasks
task_count=0

while IFS= read -r line; do
    if [[ "$line" =~ ^###\ Task\ [0-9]+:\ (.+)$ ]]; then
        task_title="${BASH_REMATCH[1]}"

        # Read next lines for priority and count
        read -r priority_line
        read -r count_line

        priority=$(echo "$priority_line" | grep -oP 'Priority\*\*: \K[A-Z]+')
        count=$(echo "$count_line" | grep -oP 'Affected Tests\*\*: \K[0-9]+')

        # Create task content
        content="Fix ${task_title} (${count} tests)"
        activeForm="Fixing ${task_title} (${count} tests)"

        # Determine initial status based on priority
        status="pending"

        # Store task
        tasks[$task_count]=$(cat <<TASK_JSON
{
  "content": "$content",
  "status": "$status",
  "activeForm": "$activeForm"
}
TASK_JSON
)

        task_count=$((task_count + 1))
    fi
done < "$TASKS_FILE"

echo -e "${CYAN}Found ${task_count} tasks${NC}"

# Generate JSON array
echo -e "${BLUE}Generating JSON...${NC}"

cat > "$OUTPUT_FILE" << 'JSON_START'
{
  "todos": [
JSON_START

# Add tasks
for ((i=0; i<task_count; i++)); do
    echo "${tasks[$i]}" >> "$OUTPUT_FILE"
    if [ $i -lt $((task_count - 1)) ]; then
        echo "," >> "$OUTPUT_FILE"
    fi
done

cat >> "$OUTPUT_FILE" << 'JSON_END'
  ]
}
JSON_END

echo -e "${GREEN}✓ TodoWrite JSON generated: ${OUTPUT_FILE}${NC}"
echo ""

# Show preview
echo -e "${CYAN}Preview (first 3 tasks):${NC}"
echo ""
head -20 "$OUTPUT_FILE"
echo "..."
echo ""

# Generate instructions for Claude
cat > "./TODO_IMPORT_INSTRUCTIONS.md" << 'INSTRUCTIONS'
# How to Import Test Failure Tasks

## Option 1: Manual Review (Recommended)

Review the tasks and selectively add them:

```bash
cat ./FAILING_TESTS_TASKS.md
```

Then use Claude to create todos:
```
claude> Create todos for the top 5 priority tasks from FAILING_TESTS_TASKS.md
```

## Option 2: Bulk Import (Advanced)

Import all tasks at once using the generated JSON:

```bash
# Show the tasks
cat ./test-failure-todos.json

# In Claude session, you can reference this structure
```

## Option 3: Prioritized Import

Import only high-priority tasks:

```
claude> Create todos for all HIGH priority tasks from FAILING_TESTS_TASKS.md
```

## Task Management

**Update task status** as you work:
- Mark as `in_progress` when starting
- Mark as `completed` when done
- Remove if no longer relevant

**Use skills** as recommended in task descriptions:
- `systematic-debugging` for root cause analysis
- `condition-based-waiting` for timing issues
- `test-driven-development` for new features

## Parallel Agent Dispatch

For independent failures, dispatch multiple agents:

```
claude> Dispatch parallel agents for [list independent domains]
```

Example:
```
claude> Dispatch parallel agents:
1. Fix QueryException database errors (100 tests)
2. Fix GraphQL configuration (50 tests)
3. Fix PHPUnit deprecation warnings (200 tests)
```

---

Generated by: create-todos-from-failures.sh
INSTRUCTIONS

echo -e "${GREEN}✓ Instructions saved: ${YELLOW}./TODO_IMPORT_INSTRUCTIONS.md${NC}"
echo ""

# Summary
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Summary${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "  ${GREEN}✓${NC} Analyzed: ${YELLOW}$task_count${NC} task categories"
echo -e "  ${GREEN}✓${NC} Generated: ${YELLOW}$OUTPUT_FILE${NC}"
echo -e "  ${GREEN}✓${NC} Instructions: ${YELLOW}./TODO_IMPORT_INSTRUCTIONS.md${NC}"
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo ""
echo -e "  ${MAGENTA}1.${NC} Review tasks:"
echo -e "     ${YELLOW}cat ./FAILING_TESTS_TASKS.md${NC}"
echo ""
echo -e "  ${MAGENTA}2.${NC} Import into Claude session:"
echo -e "     ${YELLOW}cat ./TODO_IMPORT_INSTRUCTIONS.md${NC}"
echo ""
echo -e "  ${MAGENTA}3.${NC} Prioritize and assign:"
echo -e "     ${YELLOW}Start with HIGH priority tasks first${NC}"
echo ""
echo -e "  ${MAGENTA}4.${NC} Use skills and parallel agents:"
echo -e "     ${YELLOW}Follow skill recommendations in tasks${NC}"
echo ""
echo ""
